### PR TITLE
[WIP] Update ModelPatcher to work with changes in ComfyUI v0.3.7 onwards

### LINKED ISSUE #47: **Exception Message:** 'ModelPatcher' object has no attribute 'parent'
# ComfyUI Error Report
## Error Details
- **Node ID:** 2
- **Node Type:** Fooocus PreKSampler
- **Exception Type:** AttributeError
- **Exception Message:** 'ModelPatcher' object has no attribute 'parent'
## Stack Trace
```
  File "D:\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\ComfyUI\custom_nodes\Fooocus_Nodes\py\fooocusNodes.py", line 429, in fooocus_preKSampler
    pipeline.refresh_everything(

  File "D:\ComfyUI\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "D:\ComfyUI\custom_nodes\Fooocus_Nodes\py\modules\default_pipeline.py", line 261, in refresh_everything
    prepare_text_encoder(async_call=True)

  File "D:\ComfyUI\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "D:\ComfyUI\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "D:\ComfyUI\custom_nodes\Fooocus_Nodes\py\modules\default_pipeline.py", line 224, in prepare_text_encoder
    comfy.model_management.load_models_gpu([final_clip.patcher, final_expansion.patcher])

  File "D:\ComfyUI\comfy\model_management.py", line 459, in load_models_gpu
    loaded_model = LoadedModel(x)

  File "D:\ComfyUI\comfy\model_management.py", line 292, in __init__
    self._set_model(model)

  File "D:\ComfyUI\comfy\model_management.py", line 301, in _set_model
    if model.parent is not None:

```
## System Information
- **ComfyUI Version:** v0.3.7-33-g6d1a3f7d
- **Arguments:** D:\ComfyUI\main.py --auto-launch --preview-method auto --disable-smart-memory --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 24110956544
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

How to fix it

### LINKED ISSUE #48: 'ModelPatcher' object has no attribute 'parent'
Hi, 
I am trying to run the basic workflow basic.json. But unfortunately I receive the following error on ComfyUI.  Full report is attached. 

Would you please help me to resolve this issue? Thank you very much in advance.

image

Bests,
Cihan

[comfyui.log](https://github.com/user-attachments/files/18291747/comfyui.log)

### PR DESCRIPTION
**Pull request by Raghav-B**
Based on @Kosinkadink 's suggestions [here](https://github.com/Seedsa/Fooocus_Nodes/issues/47#issuecomment-2568249246), I have changed all instances of `ldm_patched.modules.model_patcher.ModelPatcher` to instead use a new `ldm_patched.modules.model_patcher.FooocusModelPatcher` class which inherits from `comfy.model_patcher.ModelPatcher`.

This seems to fix #47 and fix #48 .

### Overview

- While making these changes, I noted only one functional difference between the original `ldm_patched.modules.model_patcher.ModelPatcher` and the last compatible ComfyUI version `v0.3.6`.
  - This was the commenting out of `# self.model.device = device_to` in the `unpatch_model()` and `load()` methods - seeing as the Fooocus-loaded models don't have a `self.device` attribute which ComfyUI expects. 
- I therefore replicated these same changes in `FooocusModelPatcher`, while keeping the rest of the code identical to `comfy.model_patcher.ModelPatcher` ComfyUI `main`.
- I have tested my changes against all [example workflows.](https://github.com/Seedsa/Fooocus_Nodes/tree/main/workflow)
  - I added an `upscale.json` workflow as well to ensure the workflows cover all nodes within `Fooocus_Nodes`.

@Seedsa do let me know if I have missed anything here.

### Limitations

The way Fooocus_Nodes works is by currently copying modules from an old version of ComfyUI's `comfy/` directory. The fixes in this PR just make the minimal changes required to get `Fooocus_Nodes` running with ComfyUI's `v0.3.10` at the time of writing.

In the future, we should try to use more of an inheritance-style workflow to override specific parts of ComfyUI. This will ensure long term version compatibility between ComfyUI and `Fooocus_Nodes`.

### CODE REVIEW

**Comment by iwr-redmond** [comment]
Your WIP fork is already being used as a replacement for this source branch (see [here](https://github.com/Chaoses-Ib/ComfyScript/issues/85)). In the absence of @Seedsa, you may wish to:

- Incorporate the improvements from the [sdwebui-extensions fork](https://github.com/sdwebui-extensions/Fooocus_Nodes)
- Rename your branch to, e.g. ComfyUI_FooocusNodes
- Publish your improved node pack to Comfy Registry ([instructions](https://docs.comfy.org/registry/publishing))

**Comment by Raghav-B** [comment]
> * Incorporate the improvements from the [sdwebui-extensions fork](https://github.com/sdwebui-extensions/Fooocus_Nodes)

Is this fork used to add Fooocus_Nodes as an extension into AUTOMATIC1111's webUI? - asking because I'm not familiar with `sdwebui-extensions`.

> * Publish your improved node pack to Comfy Registry ([instructions](https://docs.comfy.org/registry/publishing))

I can't seem to create an account on the ComfyUI Registry right now haha - getting a CORS error.

**Comment by iwr-redmond** [comment]
No it's a straight fork of this (Seedsa) repository with some model loading fixes (see [commit log](https://github.com/Seedsa/Fooocus_Nodes/compare/main...sdwebui-extensions:Fooocus_Nodes:main)). But for your excellent recent addition, it is able to be merged with the @Seedsa original code.

**Comment by Raghav-B** [comment]
Sure I can add those changes into my branch and publish the updated node.

For my future reference, how do you know I should take the changes from the sdwebui-extensions fork? Is that fork being used by some community somewhere in lieu of @Seedsa's original repo?

**Comment by iwr-redmond** [comment]
Perhaps clone the sdwebui fork into a fresh repository, and then add your fix back in. 

The sdwebui-extensions organization maintains a large number of patched custom nodes and A1111 extensions, as well as a [fork of ComfyUI-Manager](https://github.com/sdwebui-extensions/ComfyUI-Manager) for their own use.

**Comment by iwr-redmond** [comment]
Thank you, @Seedsa and @Raghav-B!
